### PR TITLE
TitleControl: remove magic setSeparator method

### PR DESCRIPTION
**Pull request by TomasPilar**
Hi i know that this package is marked as deprecated but before i remove it from my dependencies please fix this bug on Nette 2.4.

Thanks!

### CODE REVIEW

**Comment by TomasPilar** [comment]
ping @TomasVotruba

**Comment by TomasVotruba** [comment]
Hi Tomas, great. Ready to go! I will add you here as well.

It you are still using this package, we might put it back to Zenify.

**Comment by TomasVotruba** [comment]
I can't add you now nor merge thi. I'm waiting for access from @enumag 

I'll try to resolve this ASAP :)

**Comment by TomasPilar** [comment]
@TomasVotruba @enumag Thanks guys!

**Comment by TomasVotruba** [comment]
@enumag It's by default. Happens me often :D 

Thank you!

**Pull request merged**
